name: Sunya
title: Sunya
description: Your personal cloud, in space
baseurl: ""

subscribe_links:
  folio: https://buy.stripe.com/cNiaEX3tT7VE7fR2RO0Ba0c
  links_light: https://buy.stripe.com/9B628r0hHcbUcAbgIE0Ba0d
  analytics_sublight: https://buy.stripe.com/fZu6oHe8xcbU9nZdws0Ba0e
  news: https://buy.stripe.com/cNi3cv5C1fo657J8c80Ba0f
  universe_news_and_folio: https://buy.stripe.com/5kQfZh3tT0tc1VxfEA0Ba0g
